#!/bin/sh
ROOT=$(git rev-parse --show-toplevel)

echo "Running backend tests..."
cd "$ROOT/server" && dotnet test server.Tests/server.Tests.csproj

echo "Running frontend tests..."
cd "$ROOT/client" && yarn test
